/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.movie;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.movie.data.sources.SourceMovie;
import com.movie.presentation.sections.SectionHome;
import com.movie.presentation.sections.SectionMovieOrder;
import java.awt.*;
import javax.swing.UIManager;

/**
 *
 * @author user
 */
public class MovieApplication extends javax.swing.JFrame {

  /**
   * Creates new form MovieApplication
   */
  public MovieApplication() {
    initComponents();

    initContent();
    navigateToSectionName(SectionHome.name);

    var result = new SourceMovie().readNowPlaying();
    if (result.isRight()) {
      System.out.println(result.getRight().size());
    } else {
      System.out.println(result.getLeft().message);
    }
  }

  private void initContent() {
    this.panelContent.add(SectionHome.name, new SectionHome((movie) -> {
      for (Component component : this.panelContent.getComponents()) {
        if (component instanceof SectionMovieOrder) {
          this.panelContent.remove(component);
          break;
        }
      }
      this.panelContent.add(SectionMovieOrder.name, new SectionMovieOrder(movie));
      navigateToSectionName(SectionMovieOrder.name);
    }));
    this.panelContent.add(SectionMovieOrder.name, new SectionMovieOrder(
        null
    ));
  }

  private void navigateToSectionName(String name) {
    ((CardLayout) this.panelContent.getLayout()).show(this.panelContent, name);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    buttonGroupSelectDay = new javax.swing.ButtonGroup();
    panelNavbar = new javax.swing.JPanel();
    jPanel4 = new javax.swing.JPanel();
    jPanel5 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    buttonMovies = new javax.swing.JButton();
    jPanel1 = new javax.swing.JPanel();
    buttonMyTickets = new javax.swing.JButton();
    jPanel3 = new javax.swing.JPanel();
    panelContent = new javax.swing.JPanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Movie Application");
    setMinimumSize(new java.awt.Dimension(1280, 720));
    setResizable(false);
    setSize(new java.awt.Dimension(1280, 720));

    panelNavbar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
    panelNavbar.setPreferredSize(new java.awt.Dimension(1280, 56));
    panelNavbar.setLayout(new java.awt.BorderLayout());

    jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

    jPanel5.setPreferredSize(new java.awt.Dimension(32, 100));
    jPanel4.add(jPanel5);

    jLabel1.setText("Movie Application");
    jPanel4.add(jLabel1);

    panelNavbar.add(jPanel4, java.awt.BorderLayout.LINE_START);

    jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.X_AXIS));

    buttonMovies.setText("Daftar Film");
    buttonMovies.setFocusPainted(false);
    buttonMovies.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        buttonMoviesActionPerformed(evt);
      }
    });
    jPanel2.add(buttonMovies);

    jPanel1.setPreferredSize(new java.awt.Dimension(8, 100));
    jPanel2.add(jPanel1);

    buttonMyTickets.setText("Tiket Saya");
    buttonMyTickets.setFocusPainted(false);
    buttonMyTickets.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        buttonMyTicketsActionPerformed(evt);
      }
    });
    jPanel2.add(buttonMyTickets);

    jPanel3.setPreferredSize(new java.awt.Dimension(32, 100));
    jPanel2.add(jPanel3);

    panelNavbar.add(jPanel2, java.awt.BorderLayout.EAST);

    getContentPane().add(panelNavbar, java.awt.BorderLayout.NORTH);

    panelContent.setPreferredSize(new java.awt.Dimension(1280, 0));
    panelContent.setLayout(new java.awt.CardLayout());
    getContentPane().add(panelContent, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void buttonMoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMoviesActionPerformed
    // TODO add your handling code here:
    navigateToSectionName("home");
    }//GEN-LAST:event_buttonMoviesActionPerformed

    private void buttonMyTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMyTicketsActionPerformed
    // TODO add your handling code here:
    navigateToSectionName("myTickets");
    }//GEN-LAST:event_buttonMyTicketsActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      UIManager.setLookAndFeel(new FlatMacDarkLaf());
    } catch (Exception e) {
      System.err.println(e.getMessage());
    }

//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MovieApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MovieApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MovieApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MovieApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new MovieApplication().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.ButtonGroup buttonGroupSelectDay;
  private javax.swing.JButton buttonMovies;
  private javax.swing.JButton buttonMyTickets;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JPanel panelContent;
  private javax.swing.JPanel panelNavbar;
  // End of variables declaration//GEN-END:variables
}
