/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.movie.presentation.sections;

import com.movie.data.repositories.RepositoryMovie;
import com.movie.domain.models.Movie;
import com.movie.presentation.components.MovieItem;
import com.movie.presentation.listeners.OnMovieItemClickListener;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author user
 */
public class SectionHome extends javax.swing.JPanel {

    public static final String name = "home";

    private final OnMovieItemClickListener onMovieItemClickListener;
    private final RepositoryMovie sourceMovie = new RepositoryMovie();
    private List<Movie> listMovies = new ArrayList<>();

    /**
     * Creates new form SectionHome
     *
     * @param onMovieItemClickListener
     */
    public SectionHome(
        OnMovieItemClickListener onMovieItemClickListener
    ) {
        this.onMovieItemClickListener = onMovieItemClickListener;

        // initialize components
        initComponents();

        // initialize data
        initListMovies();

        this.scrollPane.getVerticalScrollBar().setPreferredSize(new Dimension(16, 0));

    }

    private void initListMovies() {
        new Thread(() -> {
            this.title.setText("Movie: Memuat...");
            this.containerMovies.setVisible(false);
            if (this.comboBoxFilterMovie.getSelectedIndex() == 0) {
                // now playing
                var result = this.sourceMovie.readNowPlaying();
                if (result.isRight()) {
                    this.listMovies = result.getRight();
                }
            } else {
                // upcoming
                var result = this.sourceMovie.readUpcoming();
                if (result.isRight()) {
                    this.listMovies = result.getRight();
                }
            }
            initContainerMovies();
        }).start();
    }

    private void initContainerMovies() {
        if (this.containerMovies.getComponentCount() > 0) {
            this.containerMovies.removeAll();
        }

        int colCount = 5;
        int rowCount = (this.listMovies.size() + colCount - 1) / colCount;

        ((GridLayout) this.containerMovies.getLayout()).setColumns(colCount);
        ((GridLayout) this.containerMovies.getLayout()).setRows(rowCount);

        int posterHeight = 0, containerDetailsHeight = 0;
        for (Movie movie : this.listMovies) {
            MovieItem movieItem = new MovieItem(movie, (param) -> this.onMovieItemClickListener.onClick(param));
            // posterWidth = (int) movieItem.getPosterWidth();
            posterHeight = (int) movieItem.getPosterHeight();
            containerDetailsHeight = movieItem.getContainerDetailsHeight();

            this.containerMovies.add(movieItem);
        }

        if (this.listMovies.size() < colCount) {
            int n = colCount - this.listMovies.size();
            for (int a = 0; a < n; a++) {
                this.containerMovies.add(new JPanel());
            }
        }

        final var containerMoviesDimension = new Dimension(
            1280 - this.scrollPane.getVerticalScrollBar().getWidth() - ((colCount - 1) * 8),
            rowCount * (posterHeight + containerDetailsHeight) + ((rowCount - 1) * 8) + 64
        );
        this.containerMovies.setPreferredSize(containerMoviesDimension);
        this.containerMovies.setMaximumSize(containerMoviesDimension);

        this.containerMovies.setVisible(true);
        this.title.setText("Movie: " + this.comboBoxFilterMovie.getSelectedItem());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        container = new javax.swing.JPanel();
        containerHeader = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        comboBoxFilterMovie = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        containerMovies = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        scrollPane.setBorder(null);
        scrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPane.setAlignmentX(0.0F);

        container.setLayout(new javax.swing.BoxLayout(container, javax.swing.BoxLayout.Y_AXIS));

        containerHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(32, 32, 0, 32));
        containerHeader.setAlignmentX(0.0F);
        containerHeader.setMaximumSize(new java.awt.Dimension(32767, 96));
        containerHeader.setLayout(new java.awt.BorderLayout());

        comboBoxFilterMovie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedang Tayang", "Akan Datang" }));
        comboBoxFilterMovie.setAlignmentX(0.0F);
        comboBoxFilterMovie.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxFilterMovieItemStateChanged(evt);
            }
        });
        jPanel2.add(comboBoxFilterMovie);

        containerHeader.add(jPanel2, java.awt.BorderLayout.EAST);

        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setText("Movie: Sedang Tayang");
        jPanel3.add(title);

        containerHeader.add(jPanel3, java.awt.BorderLayout.WEST);

        container.add(containerHeader);

        containerMovies.setBorder(javax.swing.BorderFactory.createEmptyBorder(32, 32, 32, 32));
        containerMovies.setAlignmentX(0.0F);
        containerMovies.setLayout(new java.awt.GridLayout(1, 5, 8, 8));
        container.add(containerMovies);

        scrollPane.setViewportView(container);

        add(scrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

  private void comboBoxFilterMovieItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxFilterMovieItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            initListMovies();
        }
        // initContainerMovies();
  }//GEN-LAST:event_comboBoxFilterMovieItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxFilterMovie;
    private javax.swing.JPanel container;
    private javax.swing.JPanel containerHeader;
    private javax.swing.JPanel containerMovies;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
