/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.movie.presentation.sections;

import com.movie.data.sources.SourceMovie;
import com.movie.domain.models.Movie;
import com.movie.presentation.components.MovieItem;
import com.movie.presentation.listeners.OnMovieItemClickListener;
import java.awt.Dimension;

/**
 *
 * @author user
 */
public class SectionHome extends javax.swing.JPanel {
    
    public static final String name = "home";
    
    private final OnMovieItemClickListener onMovieItemClickListener;

    /**
     * Creates new form SectionHome
     *
     * @param onMovieItemClickListener
     */
    public SectionHome(
            OnMovieItemClickListener onMovieItemClickListener
    ) {
        this.onMovieItemClickListener = onMovieItemClickListener;
        
        initComponents();
        
        this.scrollPane.getVerticalScrollBar().setPreferredSize(new Dimension(16, 0));

        // init movies
        int posterWidth = 0, posterHeight = 0, containerDetailsHeight = 0;
        for (Movie movie : SourceMovie.list) {
            MovieItem movieItem = new MovieItem(movie, (param) -> this.onMovieItemClickListener.onClick(param));
            posterWidth = (int) movieItem.getPosterWidth();
            posterHeight = (int) movieItem.getPosterHeight();
            containerDetailsHeight = movieItem.getContainerDetailsHeight();
            
            this.containerMovies.add(movieItem);
        }
        
        this.containerMovies.setPreferredSize(new Dimension(
                1280 - this.scrollPane.getVerticalScrollBar().getWidth() - (4 * 8),
                2 * (posterHeight + containerDetailsHeight) + (1 * 8)
        ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        container = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        containerMovies = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        scrollPane.setBorder(null);
        scrollPane.setAlignmentX(0.0F);

        container.setLayout(new javax.swing.BoxLayout(container, javax.swing.BoxLayout.Y_AXIS));

        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setText("Film Populer");
        title.setBorder(javax.swing.BorderFactory.createEmptyBorder(32, 32, 0, 32));
        container.add(title);

        containerMovies.setBorder(javax.swing.BorderFactory.createEmptyBorder(32, 32, 32, 32));
        containerMovies.setAlignmentX(0.0F);
        containerMovies.setLayout(new java.awt.GridLayout(2, 5, 8, 8));
        container.add(containerMovies);

        scrollPane.setViewportView(container);

        add(scrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private javax.swing.JPanel containerMovies;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
