/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.movie.presentation.sections;

import com.movie.data.sources.SourceMovie;
import com.movie.domain.models.Movie;
import com.movie.presentation.components.MovieItem;
import com.movie.presentation.listeners.OnMovieItemClickListener;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author user
 */
public class SectionHome extends javax.swing.JPanel {

  public static final String name = "home";

  private final OnMovieItemClickListener onMovieItemClickListener;
  private final SourceMovie sourceMovie = new SourceMovie();

  /**
   * Creates new form SectionHome
   *
   * @param onMovieItemClickListener
   */
  public SectionHome(
      OnMovieItemClickListener onMovieItemClickListener
  ) {
    this.onMovieItemClickListener = onMovieItemClickListener;

    initComponents();

    this.scrollPane.getVerticalScrollBar().setPreferredSize(new Dimension(16, 0));

    // init movies
    List<Movie> listMovies = new ArrayList<Movie>();
    var readResult = this.sourceMovie.readNowPlaying();
    if (readResult.isRight()) {
      listMovies = readResult.getRight();
    }
    int colCount = 5;
    int rowCount = (int) Math.ceil(listMovies.size() / colCount);

    ((GridLayout) this.containerMovies.getLayout()).setColumns(colCount);
    ((GridLayout) this.containerMovies.getLayout()).setRows(rowCount);

    int posterWidth = 0, posterHeight = 0, containerDetailsHeight = 0;
    for (Movie movie : listMovies) {
      MovieItem movieItem = new MovieItem(movie, (param) -> this.onMovieItemClickListener.onClick(param));
      posterWidth = (int) movieItem.getPosterWidth();
      posterHeight = (int) movieItem.getPosterHeight();
      containerDetailsHeight = movieItem.getContainerDetailsHeight();

      this.containerMovies.add(movieItem);
    }

    this.containerMovies.setPreferredSize(new Dimension(
        1280 - this.scrollPane.getVerticalScrollBar().getWidth() - ((colCount - 1) * 8),
        rowCount * (posterHeight + containerDetailsHeight) + ((rowCount - 1) * 8) + 64
    ));
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    scrollPane = new javax.swing.JScrollPane();
    container = new javax.swing.JPanel();
    jPanel1 = new javax.swing.JPanel();
    title = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    jComboBox1 = new javax.swing.JComboBox<>();
    containerMovies = new javax.swing.JPanel();

    setLayout(new java.awt.BorderLayout());

    scrollPane.setBorder(null);
    scrollPane.setAlignmentX(0.0F);

    container.setLayout(new javax.swing.BoxLayout(container, javax.swing.BoxLayout.Y_AXIS));

    jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(32, 32, 0, 32));
    jPanel1.setAlignmentX(0.0F);
    jPanel1.setMaximumSize(new java.awt.Dimension(32767, 96));
    jPanel1.setLayout(new java.awt.BorderLayout());

    title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    title.setText("Film Populer");
    jPanel1.add(title, java.awt.BorderLayout.WEST);

    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedang tayang", "Paling populer" }));
    jComboBox1.setAlignmentX(0.0F);
    jPanel2.add(jComboBox1);

    jPanel1.add(jPanel2, java.awt.BorderLayout.EAST);

    container.add(jPanel1);

    containerMovies.setBorder(javax.swing.BorderFactory.createEmptyBorder(32, 32, 32, 32));
    containerMovies.setAlignmentX(0.0F);
    containerMovies.setLayout(new java.awt.GridLayout(1, 5, 8, 8));
    container.add(containerMovies);

    scrollPane.setViewportView(container);

    add(scrollPane, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel container;
  private javax.swing.JPanel containerMovies;
  private javax.swing.JComboBox<String> jComboBox1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JScrollPane scrollPane;
  private javax.swing.JLabel title;
  // End of variables declaration//GEN-END:variables
}
