/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.movie.presentation.sections;

import com.movie.MovieApplication;
import com.movie.data.repositories.RepositoryAuth;
import com.movie.domain.models.User;
import com.movie.presentation.listeners.OnLogoutListener;

/**
 *
 * @author user
 */
public class SectionMyAccount extends javax.swing.JPanel {

    public static final String name = "myAccount";

    private final OnLogoutListener logoutListener;

    /**
     * Creates new form SectionMyAccount
     */
    public SectionMyAccount(
        OnLogoutListener logoutListener
    ) {
        this.logoutListener = logoutListener;

        initComponents();
        initProfile();
    }

    private void initProfile() {
        User user = MovieApplication.USER;
        if (user != null) {
            this.labelName.setText(user.getName());
            this.labelEmail.setText(user.getEmail());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        labelName = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelBalance = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        buttonLogout = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        labelName.setText("jLabel1");
        jPanel2.add(labelName);

        labelEmail.setText("jLabel2");
        jPanel2.add(labelEmail);

        labelBalance.setText("jLabel4");
        jPanel2.add(labelBalance);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        buttonLogout.setText("Keluar");
        buttonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogoutActionPerformed(evt);
            }
        });
        jPanel4.add(buttonLogout);

        jPanel1.add(jPanel4, java.awt.BorderLayout.EAST);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 252, Short.MAX_VALUE)
        );

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogoutActionPerformed
        // TODO add your handling code here:
        final boolean result = new RepositoryAuth().logout();
        if (result) {
            this.logoutListener.call();
        }
    }//GEN-LAST:event_buttonLogoutActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLogout;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelBalance;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelName;
    // End of variables declaration//GEN-END:variables
}
